Task 15
RuslanGabd/Senla-Course-Java pull request #27
Opened 2023-12-01 19:57 UTC by RuslanGabd

2023-12-02 13:39 UTC, Mark005 requested changes
please check if your application works as expected and make a screenshot in PR comments

2023-12-02 13:39 UTC, Mark005 commented on HelloWorld.class
why do you need this?

2023-12-02 13:39 UTC, Mark005 commented on HelloWorld.java
and this

2023-12-02 13:39 UTC, Mark005 commented on Screenshot.jpg
? application should response on http method get, so you shout take the response from requests to your service by the specific URI like here
![image](https://github.com/RuslanGabd/Senla-Course-Java/assets/39222770/da1a210d-adf1-41e9-adf7-00bc9357f7fa)

2023-12-04 11:22 UTC, RuslanGabd commented on HelloWorld.class
I made a mistake in understanding the line from the task “The branch must be from the first commit of the main branch.” and made a branch from Task_1.
I deleted both files

2023-12-04 11:24 UTC, RuslanGabd commented on Screenshot.jpg
<img width="492" alt="image" src="https://github.com/RuslanGabd/Senla-Course-Java/assets/11924724/a60767de-c1ca-4974-96ff-62dba0da6bac">

2023-12-05 19:00 UTC, Mark005 approved these changes
good job!

2023-12-07 01:22 UTC, closed without merging